#Join streams
input:
  label: "input_original_ghostbusters_films"
  kafka:
    addresses:
      - ${EXTERNAL_KAFKA_BOOTSTRAP_SERVER}
    topics:
      - "Ghostbusters"
      - "Ghostbusters-II"
    target_version: 3.0.0
    consumer_group: benthos_originals_consolidation
    checkpoint_limit: 1024

output:
  label: "output_kafka_originals_consolidation"
  kafka:
    addresses:
      - ${EXTERNAL_KAFKA_BOOTSTRAP_SERVER}
    topic: "Original_Ghostbusters_Films"
    target_version: 3.0.0
    key: ${! json().ghost.name }
    partitioner: fnv1a_hash
    compression: lz4
    static_headers: {}
    metadata:
      exclude_prefixes: []
    max_in_flight: 1
    batching:
      count: 0
      byte_size: 0
      period: ""
      check: ""
